### PR TITLE
Cleaned up error messages, removed JSON stringify for jwt errors

### PR DESCRIPTION
**Pull request by eventhough**
- I added an explanation of how to use credentials in the README if the user does not want to use the decoded token

- I also updated a few of the error messages to be more clear when using the plugin.

- I added a test for expired tokens (which means I had to remove the ignoreExpiration flag)

### CODE REVIEW

**Comment by nelsonic** [comment]
Nice one @eventhough :+1: 
please increase **version** number to **4.3.2** *and* add your name to **package.json** as a ***contributor***: http://browsenpm.org/package.json#contributors

**Comment by eventhough** [comment]
One thing people need to look out for is if they are using JSON.parse right now on those two specific jwt errors. The way I do it now is I catch the exception then process the error message knowing it's not a JSON string. Closes #39

**Comment by nelsonic** [comment]
Good point.
I suspect not many people are *parsing* the error message and instead are just checking for the **403** ***StatusCode***...
Maybe we need to have a release notes section...?
Given this is a "minor" release, [***David***](https://david-dm.org/) will not tell people they *have* to upgrade. And all new people will git the new *consistent* error format. :white_check_mark:

**Comment by nelsonic** [comment]
merged. :shipit: :rocket: :star2:

**Pull request merged**
